# Generated by Django 5.2 on 2025-04-23 00:47

import django.db.models.deletion
import phonenumber_field.modelfields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None)),
                ('location', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('resume', models.TextField(blank=True, null=True)),
                ('profile_pic', models.URLField(blank=True, null=True)),
                ('preferred_career_types', models.ManyToManyField(to='CareerEasyBackend.career')),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('logo', models.URLField(blank=True, null=True)),
                ('location', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CareerEasyBackend.companycategory')),
            ],
        ),
        migrations.CreateModel(
            name='CareerCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('career', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CareerEasyBackend.career')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CareerEasyBackend.companycategory')),
            ],
        ),
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('level', models.CharField(choices=[('ng', 'new graduate'), ('j', 'junior'), ('i', 'intermediate'), ('s', 'senior'), ('u', 'unspecified')], max_length=2)),
                ('description', models.TextField(blank=True, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('career', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CareerEasyBackend.career')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CareerEasyBackend.company')),
            ],
        ),
        migrations.AddConstraint(
            model_name='company',
            constraint=models.UniqueConstraint(fields=('category', 'name', 'location'), name='no_company_name_collision'),
        ),
        migrations.AddConstraint(
            model_name='careercategory',
            constraint=models.UniqueConstraint(fields=('category', 'career'), name='unique_career_category_career'),
        ),
    ]
