# Generated by Django 5.2 on 2025-04-30 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CareerEasyBackend', '0002_applicantaccount_employeraccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='ai_highlights',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='highest_education',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='skills',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='yoe',
            field=models.IntegerField(default=0),
        ),
    ]
