# Generated by Django 5.2 on 2025-04-30 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CareerEasyBackend', '0003_candidate_ai_highlights_candidate_highest_education_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidate',
            old_name='yoe',
            new_name='experience_months',
        ),
        migrations.AddField(
            model_name='jobposting',
            name='yoe',
            field=models.IntegerField(default=0),
        ),
    ]
