# Generated by Django 5.2 on 2025-04-30 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CareerEasyBackend', '0004_rename_yoe_candidate_experience_months_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobposting',
            name='yoe',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
