# Generated by Django 5.2 on 2025-05-02 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CareerEasyBackend', '0006_candidate_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='standardized_ai_highlights',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='standardized_highest_education',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='standardized_resume',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='standardized_skills',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='standardized_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
