# Generated by Django 5.2 on 2025-05-08 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CareerEasyBackend', '0008_query_candidateaccount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ApplicantAccount',
        ),
    ]
