# Generated by Django 5.2 on 2025-05-22 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CareerEasyBackend', '0009_candidate_created_at_candidate_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='anonymous_resume',
            field=models.TextField(blank=True, null=True),
        ),
    ]
