# Generated by Django 5.2 on 2025-05-22 23:29

import django_crypto_fields.fields.encrypted_text_field
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CareerEasyBackend', '0011_alter_candidate_email_alter_candidate_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='resume',
            field=django_crypto_fields.fields.encrypted_text_field.EncryptedTextField(blank=True, help_text=' (Encryption: AES local)', max_length=71, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='standardized_resume',
            field=django_crypto_fields.fields.encrypted_text_field.EncryptedTextField(blank=True, help_text=' (Encryption: AES local)', max_length=71, null=True),
        ),
    ]
