# Generated by Django 5.2 on 2025-06-19 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CareerEasyBackend', '0013_candidate_standardized_anonymous_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateaccount',
            name='password_reset_token',
            field=models.TextField(blank=True, null=True),
        ),
    ]