# Generated by Django 5.2 on 2025-06-19 01:59

import django_crypto_fields.fields.encrypted_text_field
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CareerEasyBackend', '0014_candidateaccount_password_reset_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='original_resume_path',
            field=django_crypto_fields.fields.encrypted_text_field.EncryptedTextField(blank=True, help_text=' (Encryption: AES local)', max_length=71, null=True),
        ),
    ]
